version: 2

jobs:
  test-puppet3: &test_setup
    working_directory: ~/puppet-nsidc-jenkins
    docker:
      - image: ruby:2.1  # puppet 3 is incompatible with ruby 2.2+
        environment:
          BUNDLE_GEMFILE: Gemfile3
          FIXTURES_YML: fixtures3.yml
    steps:
      - run:
          name: Install git
          command: apt-get install -y git
      - checkout
      - run:
          name: Install RubyGem dependencies
          command: bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Linter and Parser
          command: bundle exec rake lint
      - run:
          name: Run metadata_lint, release_checks.
          command: bundle exec rake test

  test-puppet4:
    <<: *test_setup
    docker:
      - image: ruby:2.4-jessie
        environment:
          BUNDLE_GEMFILE: Gemfile4
          FIXTURES_YML: fixtures4.yml

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-puppet3
      - test-puppet4
